### PR TITLE
Drop support for EOL Python 2.6

### LINKED ISSUE #29: Drop python 2.6 support
Many other libraries are dropping support for this version. Removing this from Travis checks will aid in keeping aligned with packages `gplearn` depends upon.

### PR DESCRIPTION
**Pull request by hugovk**
Fixes #29.

The pip installs for gplearn from PyPI for the last year shows no demand:
```
$ pypinfo -d 365 --percent --pip gplearn pyversion
python_version percent download_count
-------------- ------- --------------
2.7              43.0%            776
3.6              26.9%            485
3.5              26.1%            471
3.4               3.9%             71

```

### CODE REVIEW

**Comment by hugovk** [comment]
Travis CI is failing on on jobs:

*  `PYTHON_VERSION="2.7" COVERAGE="true" LATEST="true"`
    * This fails the same way on latest master: https://travis-ci.org/hugovk/gplearn/builds/294030349

**Comment by trevorstephens** [comment]
Awesome, thanks a bunch @hugovk ! Looks like the failure might be due to the very stale version of sklearn that this package allows. I am working on #31 now and will let you know once I am happy with it.

**Comment by trevorstephens** [comment]
At this stage I think I will remove almost all of the bundled utils and so you may need to rebase this PR. Shall let you know.

**Comment by trevorstephens** [comment]
Looks like #53 fails due to sklearn dropping Python 2.6 in 0.19 so I'm just going to merge this and then fix the failing tests in the #53 PR. Thanks for the contribution @hugovk ... BTW what package do you use to query PyPI?

**Comment by hugovk** [comment]
I use pypinfo, and I agree the setup was relatively painless :)

https://github.com/ofek/pypinfo

You can then easily query loads of different things, like:
```bash
⌂76% [hugo:/tmp] % pypinfo -d 365 --percent --pip gplearn system
system_name percent download_count
----------- ------- --------------
Linux         60.8%          1,119
Windows       27.3%            502
Darwin        12.0%            220

⌂72% [hugo:/tmp] 36s % pypinfo -d 365 --percent --pip gplearn version
version percent download_count
------- ------- --------------
0.2       72.4%          1,333
0.1.0     27.6%            508

⌂65% [hugo:/tmp] 49s % pypinfo -d 365 --percent --pip gplearn country
country percent download_count
------- ------- --------------
US        41.7%            674
None       7.7%            125
GB         7.6%            123
CN         6.6%            107
SE         5.8%             93
RU         4.0%             64
BR         3.6%             58
AU         3.3%             54
IN         3.0%             49
FR         2.7%             43
DE         2.6%             42
CA         1.9%             31
ES         1.5%             24
JP         1.4%             22
KR         1.3%             21
IL         1.1%             18
NL         1.1%             18
HK         1.1%             17
SG         1.0%             16
PL         1.0%             16

⌂68% [hugo:/tmp] 32s %
⌂93% [hugo:/tmp] 32s % pypinfo -d 365 --percent --pip gplearn distro
distro_name                     percent download_count
------------------------------- ------- --------------
Ubuntu                            34.6%            630
None                              30.5%            555
macOS                             10.3%            188
Debian GNU/Linux                   9.4%            171
CentOS Linux                       5.3%             96
debian                             1.8%             33
OS X                               1.7%             31
Fedora                             1.2%             21
Linux Mint                         1.0%             19
Arch Linux                         0.8%             15
Alpine Linux                       0.7%             13
Gentoo                             0.4%              8
CentOS                             0.4%              7
Red Hat Enterprise Linux Server    0.4%              7
openSUSE Tumbleweed                0.3%              6
Raspbian GNU/Linux                 0.3%              6
LinuxMint                          0.2%              4
Manjaro Linux                      0.2%              4
openSUSE Leap                      0.2%              3
Gentoo Base System                 0.2%              3
```

**Comment by trevorstephens** [comment]
Excellent! Thanks very much for the info, shall check it out :+1:

**Pull request merged**
